### ISSUE TITLE
[Feature] Conditional Banner activation

### ISSUE THREAD

**Issue by melliiii** [Sebbo94BY/teamspeak-dynamic-banner#168]
A system for conditional banner activation would be really nice, maybe to only display a banner in a certain time range (for example only at night time), when a certain user is online or maybe even with a integration for twitch, to display banners that can inform the teamspeak users that someone in the server is live (which would integrate really nicely with the banner specific redirects), as the options for announcing that youre live on twitch are really limited on teamspeak.

**Comment by melliiii** [comment]
> Do you have a use-case scenario for this? Currently I don't see any good use-case for this. So why should a specific template be only shown to all users, when e. g. Max Mustermann is online?

Hmm youre right maybe not that useful :D My usecase would have been to maybe display the controls to a music bot in the banner. On my server the music bot leaves as soon as someone is streaming live on twitch to prevent trolling on stream ^^ 

> * Based on which information do you want to decide, that specific Streamers are online or not? Do you want to manage the Streamer list in this project? Or does your TeamSpeak clients for example have a client description, which contains the twitch link?

i would like to manage the streamer list in the bot, it could be solved in two ways: Either to really check via the twitch api if a streamer thats in a list is streaming on twitch in which case a banner condition would be met and it would display the banner

or the cheaper less resource intensive condition would be to check if certain users got a certain role assigned (e.g. "LIVE"/"On Air" Role) and then activate a banner. this would save you the trouble of coding a twitch api checker and you could use your event based bot to set the condition to true which would mean we dont need another check before each banner switch

> * And based on the twitch Streamer status, the respective template gets automatically enabled or disabled, correct?

yes it would activate a template inside a banner (like flip the switch we have to (de-)activate a template)

> When a client goes live, the bot automatically assignes the client a group, which you specify. When he stops streaming, the bot automatically removes the group from the client.

i wrote a java bot for that too, but it only checks if a user assigned themselves the role and sends them a message if they didnt and if they dont assign it in the next 5 minutes an admin gets a message. thats because of the delay between going live and getting the role assigned i had initially. My music bot on the other hand uses the twitch api to decide if it should leave.

that bot got a config file where i assign the unique ids to twitch usernames, so not everybody on the server can trigger bot actions if i dont want them to ^^

**Comment by Sebbo94BY** [comment]
For the twitch integration, I've created a new feature request: #178 :-)

Enabling / Disabling specific banners based on if certain users are online don't make sense in my opinion. However, if you have a cool use-case, feel free to create a new feature request with a detailed explanation / use-case story and then I'll recheck and overthink my opinion. :-)
