### ISSUE TITLE
[Feature] Add support for current / preferred timezone in UI

### ISSUE THREAD

**Issue by Sebbo94BY** [Sebbo94BY/teamspeak-dynamic-banner#172]
**Is your feature request related to a problem? Please describe.**
Some people are confused about different timezones - especially when they e. g. life in Germany where they additional have the summer and winter (daylight savings) with +1 or +2 hours.

This application currently shows all times in UTC+0 format. So people at different timezones start converting each printed time into their respective time.

**Describe the solution you'd like**
In a perfect world, each user automatically gets each time displayed in his local timezone, so that nobody needs to convert it from e. g. UTC+0 to UTC+2.

**Describe alternatives you've considered**
An alternative would be, if each user could set his preferred timezone in his profile.

**Additional context**
N/A

**Comment by melliiii** [comment]
IP lookup apis like https://ipgeolocation.io/timezone-api.html have a feature that you can get the timezone of an ip address. if youre so inclined you could also use javascript to determine a users timezone, but that method is not really accurate (ive heard)
