### ISSUE TITLE
Fresh installation failed in step "Installer: Requirements" with SMTP Error

### ISSUE THREAD

**Issue by MajorOli** [Sebbo94BY/teamspeak-dynamic-banner#200]
**Describe the bug**
At the installation routine it's not possible to pass the Installer: Requirements because the SMTP check is always failed.
It's testet with the docker image and other SMTP settings at .env

**Comment by Sebbo94BY** [comment]
I've fixed and improved the entire check. Now it should work as expected for all cases. :-)
