### ISSUE TITLE
Missing jquery.dataTables.min.css

### ISSUE THREAD

**Issue by MajorOli** [Sebbo94BY/teamspeak-dynamic-banner#81]
ich konnte keine CSS mit dem Pattern datatables finden.
Laut https://datatables.net/ muss //cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css enthalten sein.

**Comment by Sebbo94BY** [comment]
`npm` installiert diese Abhängigkeit: https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/laravel/package.json#L19C1-L20C1

https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docs/INSTALLATION.md#install-dependencies:

1. `npm install`
2. `npm run build`

https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/laravel/resources/js/app.js inkludiert dann zum Beispiel die JavaScript Datei(en).

CSS scheint tatsächlich zu fehlen. Das müsste bei Bedarf hier rein: https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/laravel/resources/sass/app.scss
